//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaranuMotorsWithEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int FuelId { get; set; }
        public Nullable<decimal> EngineVolume { get; set; }
        public int TransmissionId { get; set; }
        public int ColorId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public int ModelId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Model Model { get; set; }
        public virtual Transmission Transmission { get; set; }
    }
}
